apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: a0502153-c29b-4372-b50a-777c890145ca
          target-environment: PREPROD
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: jenkins
          artifact-id: a0502153-c29b-4372-b50a-777c890145ca
          target-environment: Production